version: '3'

output: prefixed

vars:
  COVER_NAME: 'coverage'
  COVER_FILE: '{{.COVER_NAME}}.out'
  COVER_HTML: '{{.COVER_NAME}}.html'

includes:
  lint: ./lint

tasks:

  test:
    desc: 'runs `go test` in race detection and atomic coverage collection mode'
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmd: go test -v ./... -race -coverprofile={{.COVER_FILE}} -covermode=atomic

  cover:
    desc: 'runs the test task, the `cover` Go tool and displays the generated HTML report'
    dir: '{{.USER_WORKING_DIR}}'
    deps: 
      - task: test
    cmds:
      - cmd: go tool cover -html={{.COVER_FILE}} -o {{.COVER_HTML}}
      - cmd: cmd /c start {{.COVER_HTML}}
        platforms: [windows]
